steps:
  - name: "gcr.io/cloud-builders/gcloud"
    args: ["config", "set", "app/cloud_build_timeout", "3600"]

  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args: ["-c", "docker pull gcr.io/fanbytes/dev-ops-api/${_ENVIRONMENT}:latest || exit 0"]

  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/fanbytes/devops-api/${_ENVIRONMENT}:${_COMMIT_SHA}",
        "-t",
        "gcr.io/fanbytes/devops-api/${_ENVIRONMENT}:latest",
        "--cache-from",
        "gcr.io/fanbytes/devops-api/${_ENVIRONMENT}:latest",
        ".",
      ]

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "--all-tags", "gcr.io/fanbytes/dev-ops-api/${_ENVIRONMENT}"]

  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "app",
        "deploy",
        "app.${_ENVIRONMENT}.yaml",
        "--image-url",
        "gcr.io/fanbytes/dev-ops-api/${_ENVIRONMENT}:${_COMMIT_SHA}",
      ]

timeout: 3600s
options:
  substitutionOption: "ALLOW_LOOSE"
  machineType: "N1_HIGHCPU_8"
tags: ["dev-ops", "backend"]
